export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CURRENT_STEP = "CURRENT_STEP"

export const TOGGLE_MENU = "TOGGLE_MENU";

export const CHANGE_LANG="CHANGE_LANGUAGE";