export const countryList = [
  { name: ["Switzerland", "Suisse"], code: "CH" },
  { name: ["Afghanistan", "Afghanistan"], code: "AF" },
  { name: ["Åland Islands", "Iles Aland"], code: "AX" },
  { name: ["Albania", "Albanie"], code: "AL" },
  { name: ["Algeria", "Algérie"], code: "DZ" },
  { name: ["American Samoa", "Samoa Américaines"], code: "AS" },
  { name: ["Andorra", "Andorre"], code: "AD" },
  { name: ["Angola", "Angola"], code: "AO" },
  { name: ["Anguilla", "Anguilla"], code: "AI" },
  { name: ["Antarctica", "Antarctique"], code: "AQ" },
  { name: ["Antigua and Barbuda", "Antigua-et-Barbuda"], code: "AG" },
  { name: ["Argentina", "Argentine"], code: "AR" },
  { name: ["Armenia", "Arménie"], code: "AM" },
  { name: ["Aruba", "Aruba"], code: "AW" },
  { name: ["Australia", "Australie"], code: "AU" },
  { name: ["Austria", "L'Autriche"], code: "AT" },
  { name: ["Azerbaijan", "Azerbaïdjan"], code: "AZ" },
  { name: ["Bahamas", "Bahamas"], code: "BS" },
  { name: ["Bahrain", "Bahrein"], code: "BH" },
  { name: ["Bangladesh", "Bangladesh"], code: "BD" },
  { name: ["Barbados", "Barbade"], code: "BB" },
  { name: ["Belarus", "Biélorussie"], code: "BY" },
  { name: ["Belgium", "Belgique"], code: "BE" },
  { name: ["Belize", "Belize"], code: "BZ" },
  { name: ["Benin", "Bénin"], code: "BJ" },
  { name: ["Bermuda", "Bermudes"], code: "BM" },
  { name: ["Bhutan", "Bhoutan"], code: "BT" },
  { name: ["Bolivia", "Bolivie"], code: "BO" },
  { name: ["Bosnia and Herzegovina", "Bosnie Herzégovine"], code: "BA" },
  { name: ["Botswana", "Botswana"], code: "BW" },
  { name: ["Bouvet Island", "Bouvet Island"], code: "BV" },
  { name: ["Brazil", "Brésil"], code: "BR" },
  { name: ["British Indian Ocean Territory", "Territoire britannique de l'océan Indien"], code: "IO" },
  { name: ["Brunei Darussalam", "Brunei Darussalam"], code: "BN" },
  { name: ["Bulgaria", "Bulgarie"], code: "BG" },
  { name: ["Burkina Faso", "Burkina Faso"], code: "BF" },
  { name: ["Burundi", "Burundi"], code: "BI" },
  { name: ["Cambodia", "Cambodge"], code: "KH" },
  { name: ["Cameroon", "Cameroun"], code: "CM" },
  { name: ["Canada", "Canada"], code: "CA" },
  { name: ["Cape Verde", "Cap-Vert"], code: "CV" },
  { name: ["Cayman Islands", "Îles Caïmans"], code: "KY" },
  { name: ["Central African Republic", "République centrafricaine"], code: "CF" },
  { name: ["Chad", "Tchad"], code: "TD" },
  { name: ["Chile", "Chili"], code: "CL" },
  { name: ["China", "Chine"], code: "CN" },
  { name: ["Christmas Island", "L'île de noël"], code: "CX" },
  { name: ["Cocos (Keeling) Islands", "Îles Cocos (Keeling)"], code: "CC" },
  { name: ["Colombia", "Colombie"], code: "CO" },
  { name: ["Comoros", "Les Comores"], code: "KM" },
  { name: ["Congo", "Congo"], code: "CG" },
  { name: ["Congo, The Democratic Republic of the", "Congo, République démocratique du"], code: "CD" },
  { name: ["Cook Islands", "les Îles Cook"], code: "CK" },
  { name: ["Costa Rica", "Costa Rica"], code: "CR" },
  { name: ["Cote D'Ivoire", "Côte d'Ivoire"], code: "CI" },
  { name: ["Croatia", "Croatie"], code: "HR" },
  { name: ["Cuba", "Cuba"], code: "CU" },
  { name: ["Cyprus", "Chypre"], code: "CY" },
  { name: ["Czech Republic", "République Tchèque"], code: "CZ" },
  { name: ["Denmark", "Danemark"], code: "DK" },
  { name: ["Djibouti", "Djibouti"], code: "DJ" },
  { name: ["Dominica", "La Dominique"], code: "DM" },
  { name: ["Dominican Republic", "République Dominicaine"], code: "DO" },
  { name: ["Ecuador", "Équateur"], code: "EC" },
  { name: ["Egypt", "Egypte"], code: "EG" },
  { name: ["El Salvador", "Le Salvador"], code: "SV" },
  { name: ["Equatorial Guinea", "Guinée Équatoriale"], code: "GQ" },
  { name: ["Eritrea", "Erythrée"], code: "ER" },
  { name: ["Estonia", "Estonie"], code: "EE" },
  { name: ["Ethiopia", "Ethiopie"], code: "ET" },
  { name: ["Falkland Islands (Malvinas)", "Îles Falkland (Malvinas)"], code: "FK" },
  { name: ["Faroe Islands", "Îles Féroé"], code: "FO" },
  { name: ["Fiji", "Fidji"], code: "FJ" },
  { name: ["Finland", "Finlande"], code: "FI" },
  { name: ["France", "France"], code: "FR" },
  { name: ["French Guiana", "Guinée Française"], code: "GF" },
  { name: ["French Polynesia", "Polynésie française"], code: "PF" },
  { name: ["French Southern Territories", "Terres Australes Françaises"], code: "TF" },
  { name: ["Gabon", "Gabon"], code: "GA" },
  { name: ["Gambia", "Gambie"], code: "GM" },
  { name: ["Georgia", "Géorgie"], code: "GE" },
  { name: ["Germany", "Allemagne"], code: "DE" },
  { name: ["Ghana", "Ghana"], code: "GH" },
  { name: ["Gibraltar", "Gibraltar"], code: "GI" },
  { name: ["Greece", "Grèce"], code: "GR" },
  { name: ["Greenland", "Groenland"], code: "GL" },
  { name: ["Grenada", "Grenade"], code: "GD" },
  { name: ["Guadeloupe", "Guadeloupe"], code: "GP" },
  { name: ["Guam", "Guam"], code: "GU" },
  { name: ["Guatemala", "Guatemala"], code: "GT" },
  { name: ["Guernsey", "Guernesey"], code: "GG" },
  { name: ["Guinea", "Guinée"], code: "GN" },
  { name: ["Guinea-Bissau", "Guinée Bissau"], code: "GW" },
  { name: ["Guyana", "Guyane"], code: "GY" },
  { name: ["Haiti", "Haïti"], code: "HT" },
  { name: ["Heard Island and Mcdonald Islands", "Heard Island et les îles Mcdonald"], code: "HM" },
  { name: ["Holy See (Vatican City State)", "Saint-Siège (État de la cité du Vatican)"], code: "VA" },
  { name: ["Honduras", "Honduras"], code: "HN" },
  { name: ["Hong Kong", "Hong Kong"], code: "HK" },
  { name: ["Hungary", "Hongrie"], code: "HU" },
  { name: ["Iceland", "Islande"], code: "IS" },
  { name: ["India", "Inde"], code: "IN" },
  { name: ["Indonesia", "Indonésie"], code: "ID" },
  { name: ["Iran, Islamic Republic Of", "Iran (République islamique d"], code: "IR" },
  { name: ["Iraq", "Irak"], code: "IQ" },
  { name: ["Ireland", "Irlande"], code: "IE" },
  { name: ["Isle of Man", "Île de man"], code: "IM" },
  { name: ["Israel", "Israël"], code: "IL" },
  { name: ["Italy", "Italie"], code: "IT" },
  { name: ["Jamaica", "Jamaïque"], code: "JM" },
  { name: ["Japan", "Japon"], code: "JP" },
  { name: ["Jersey", "Jersey"], code: "JE" },
  { name: ["Jordan", "Jordan"], code: "JO" },
  { name: ["Kazakhstan", "Kazakhstan"], code: "KZ" },
  { name: ["Kenya", "Kenya"], code: "KE" },
  { name: ["Kiribati", "Kiribati"], code: "KI" },
  { name: ["Korea, Democratic People'S Republic of", "République populaire démocratique de Corée"], code: "KP" },
  { name: ["Korea, Republic of", "Corée, République de"], code: "KR" },
  { name: ["Kuwait", "Koweit"], code: "KW" },
  { name: ["Kyrgyzstan", "Kirghizistan"], code: "KG" },
  { name: ["Lao People'S Democratic Republic", "République démocratique populaire lao"], code: "LA" },
  { name: ["Latvia", "Lettonie"], code: "LV" },
  { name: ["Lebanon", "Liban"], code: "LB" },
  { name: ["Lesotho", "Lesotho"], code: "LS" },
  { name: ["Liberia", "Libéria"], code: "LR" },
  { name: ["Libyan Arab Jamahiriya", "Jamahiriya Arabe Libyenne"], code: "LY" },
  { name: ["Liechtenstein", "Liechtenstein"], code: "LI" },
  { name: ["Lithuania", "Lituanie"], code: "LT" },
  { name: ["Luxembourg", "Luxembourg"], code: "LU" },
  { name: ["Macao", "Macao"], code: "MO" },
  { name: ["Macedonia, The Former Yugoslav Republic of", "Macédoine, l'ex-République yougoslave de"], code: "MK" },
  { name: ["Madagascar", "Madagascar"], code: "MG" },
  { name: ["Malawi", "Malawi"], code: "MW" },
  { name: ["Malaysia", "Malaisie"], code: "MY" },
  { name: ["Maldives", "Maldives"], code: "MV" },
  { name: ["Mali", "Mali"], code: "ML" },
  { name: ["Malta", "Malte"], code: "MT" },
  { name: ["Marshall Islands", "Iles Marshall"], code: "MH" },
  { name: ["Martinique", "Martinique"], code: "MQ" },
  { name: ["Mauritania", "Mauritanie"], code: "MR" },
  { name: ["Mauritius", "Maurice"], code: "MU" },
  { name: ["Mayotte", "Mayotte"], code: "YT" },
  { name: ["Mexico", "Mexique"], code: "MX" },
  { name: ["Micronesia, Federated States of", "Micronésie, États fédérés de"], code: "FM" },
  { name: ["Moldova, Republic of", "Moldova, République de"], code: "MD" },
  { name: ["Monaco", "Monaco"], code: "MC" },
  { name: ["Mongolia", "Mongolie"], code: "MN" },
  { name: ["Montserrat", "Montserrat"], code: "MS" },
  { name: ["Morocco", "Maroc"], code: "MA" },
  { name: ["Mozambique", "Mozambique"], code: "MZ" },
  { name: ["Myanmar", "Myanmar"], code: "MM" },
  { name: ["Namibia", "Namibie"], code: "NA" },
  { name: ["Nauru", "Nauru"], code: "NR" },
  { name: ["Nepal", "Népal"], code: "NP" },
  { name: ["Netherlands", "Pays-Bas"], code: "NL" },
  { name: ["Netherlands Antilles", "Antilles néerlandaises"], code: "AN" },
  { name: ["New Caledonia", "Nouvelle Calédonie"], code: "NC" },
  { name: ["New Zealand", "Nouvelle-Zélande"], code: "NZ" },
  { name: ["Nicaragua", "Nicaragua"], code: "NI" },
  { name: ["Niger", "Niger"], code: "NE" },
  { name: ["Nigeria", "Nigeria"], code: "NG" },
  { name: ["Niue", "Niue"], code: "NU" },
  { name: ["Norfolk Island", "l'ile de Norfolk"], code: "NF" },
  { name: ["Northern Mariana Islands", "Îles Mariannes du Nord"], code: "MP" },
  { name: ["Norway", "Norvège"], code: "NO" },
  { name: ["Oman", "Oman"], code: "OM" },
  { name: ["Pakistan", "Pakistan"], code: "PK" },
  { name: ["Palau", "Palau"], code: "PW" },
  { name: ["Palestinian Territory, Occupied", "Territoire palestinien occupé"], code: "PS" },
  { name: ["Panama", "Panama"], code: "PA" },
  { name: ["Papua New Guinea", "Papouasie Nouvelle Guinée"], code: "PG" },
  { name: ["Paraguay", "Le Paraguay"], code: "PY" },
  { name: ["Peru", "Pérou"], code: "PE" },
  { name: ["Philippines", "Philippines"], code: "PH" },
  { name: ["Pitcairn", "Pitcairn"], code: "PN" },
  { name: ["Poland", "Pologne"], code: "PL" },
  { name: ["Portugal", "le Portugal"], code: "PT" },
  { name: ["Puerto Rico", "Porto Rico"], code: "PR" },
  { name: ["Qatar", "Qatar"], code: "QA" },
  { name: ["Reunion", "Réunion"], code: "RE" },
  { name: ["Romania", "Roumanie"], code: "RO" },
  { name: ["Russian Federation", "Fédération Russe"], code: "RU" },
  { name: ["RWANDA", "RWANDA"], code: "RW" },
  { name: ["Saint Helena", "Sainte Hélène"], code: "SH" },
  { name: ["Saint Kitts and Nevis", "Saint-Christophe-et-Niévès"], code: "KN" },
  { name: ["Saint Lucia", "Sainte-Lucie"], code: "LC" },
  { name: ["Saint Pierre and Miquelon", "Saint Pierre et Miquelon"], code: "PM" },
  { name: ["Saint Vincent and the Grenadines", "Saint-Vincent-et-les-Grenadines"], code: "VC" },
  { name: ["Samoa", "Samoa"], code: "WS" },
  { name: ["San Marino", "Saint Marin"], code: "SM" },
  { name: ["Sao Tome and Principe", "Sao Tomé et Principe"], code: "ST" },
  { name: ["Saudi Arabia", "Arabie Saoudite"], code: "SA" },
  { name: ["Senegal", "Sénégal"], code: "SN" },
  { name: ["Serbia and Montenegro", "Serbie et Monténégro"], code: "CS" },
  { name: ["Seychelles", "les Seychelles"], code: "SC" },
  { name: ["Sierra Leone", "Sierra Leone"], code: "SL" },
  { name: ["Singapore", "Singapour"], code: "SG" },
  { name: ["Slovakia", "Slovaquie"], code: "SK" },
  { name: ["Slovenia", "La Slovénie"], code: "SI" },
  { name: ["Solomon Islands", "îles Salomon"], code: "SB" },
  { name: ["Somalia", "Somalie"], code: "SO" },
  { name: ["South Africa", "Afrique du Sud"], code: "ZA" },
  { name: ["South Georgia and the South Sandwich Islands", "Géorgie du Sud et les îles Sandwich du Sud"], code: "GS" },
  { name: ["Spain", "Espagne"], code: "ES" },
  { name: ["Sri Lanka", "Sri Lanka"], code: "LK" },
  { name: ["Sudan", "Soudan"], code: "SD" },
  { name: ["Suriname", "Suriname"], code: "SR" },
  { name: ["Svalbard and Jan Mayen", "Svalbard et Jan Mayen"], code: "SJ" },
  { name: ["Swaziland", "Swaziland"], code: "SZ" },
  { name: ["Sweden", "Suède"], code: "SE" },

  { name: ["Syrian Arab Republic", "République arabe syrienne"], code: "SY" },
  { name: ["Taiwan, Province of China", "Taiwan, Province de Chine"], code: "TW" },
  { name: ["Tajikistan", "Tadjikistan"], code: "TJ" },
  { name: ["Tanzania, United Republic of", "Tanzanie, République Unie de"], code: "TZ" },
  { name: ["Thailand", "Thaïlande"], code: "TH" },
  { name: ["Timor-Leste", "Timor-Leste"], code: "TL" },
  { name: ["Togo", "Aller"], code: "TG" },
  { name: ["Tokelau", "Tokélaou"], code: "TK" },
  { name: ["Tonga", "Tonga"], code: "TO" },
  { name: ["Trinidad and Tobago", "Trinité-et-Tobago"], code: "TT" },
  { name: ["Tunisia", "Tunisie"], code: "TN" },
  { name: ["Turkey", "Turquie"], code: "TR" },
  { name: ["Turkmenistan", "Turkménistan"], code: "TM" },
  { name: ["Turks and Caicos Islands", "îles Turques-et-Caïques"], code: "TC" },
  { name: ["Tuvalu", "Tuvalu"], code: "TV" },
  { name: ["Uganda", "Ouganda"], code: "UG" },
  { name: ["Ukraine", "Ukraine"], code: "UA" },
  { name: ["United Arab Emirates", "Emirats Arabes Unis"], code: "AE" },
  { name: ["United Kingdom", "Royaume-Uni"], code: "GB" },
  { name: ["United States", "États Unis"], code: "US" },
  { name: ["United States Minor Outlying Islands", "Îles mineures éloignées des États-Unis"], code: "UM" },
  { name: ["Uruguay", "Uruguay"], code: "UY" },
  { name: ["Uzbekistan", "Ouzbekistan"], code: "UZ" },
  { name: ["Vanuatu", "Vanuatu"], code: "VU" },
  { name: ["Venezuela", "Venezuela"], code: "VE" },
  { name: ["Viet Nam", "Viet Nam"], code: "VN" },
  { name: ["Virgin Islands, British", "Îles vierges britanniques"], code: "VG" },
  { name: ["Virgin Islands, U.S.", "Îles Vierges américaines"], code: "VI" },
  { name: ["Wallis and Futuna", "Wallis et Futuna"], code: "WF" },
  { name: ["Western Sahara", "Sahara occidental"], code: "EH" },
  { name: ["Yemen", "Yémen"], code: "YE" },
  { name: ["Zambia", "Zambie"], code: "ZM" },
  { name: ["Zimbabwe", "Zimbabwe"], code: "ZW" }
];

export const months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

export const years = [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30];
