const language = [
  //English
  {
    app_title: "EXCHANGE TON PORT",
    english_native: "English",
    french_native: "Français",
    login: "Login",
    logout: "Logout",
    register: "Register",
    profil: "Profile",
    civility: "Civility",
    mr: "Mr",
    mrs: "Mrs",
    ms: "Ms",
    enter_your_first_name: "Enter your First Name",
    first_name: "First Name",
    enter_your_last_name: "Enter your Last Name",
    last_name: "Last Name",
    language: "Language",
    english: "English",
    french: "French",
    enter_your_email: "Enter your Email",
    email: "Email",
    phone_number: "Phone Number",
    enter_your_phone_number: "Enter your Phone Number",
    address: "Address",
    address2: "Address2",
    enter_your_postcode: "Enter your Postcode",
    postcode: "Postcode",
    enter_your_city: "Enter your Town/City",
    town_city: "Town/City",
    country: "Country",
    profile_picture: "Profile Pictrue",
    add_profile_picture: "Add Profile Picture",
    security: "Security",
    password: "Password",
    enter_your_password: "Enter your password",
    change_password: "Change Password",
    old_password: "Old Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    change: "Change",
    change_email: "Change Email",
    new_email: "New Email",
    save_my_profile: "Save my Profile",
    more: "More",
    boat_specification: "Boat Specification",
    boat_name: "Boat Name",
    type: "Type",
    sail: "Sail",
    motor: "Motor",
    width: "Width",
    draught: "Draught",
    harbour: "My Harbour",
    my_place: "My place",
    save: "Save",
    ads: "My Ads",
    offer: "Offer",
    demand: "Demand",
    boat: "Boat",
    arrival: "Arrival",
    return: "Return",
    user_info: "User Info",
    boat_info: "Boat Info",
    schedule: "Listings",
    no: "No",
    start_harbour: "Start Harbour",
    end_harbour: "End Harbour",
    name: "Name",
    i_accept: "I accept",
    terms: "terms and conditions",
    remember_me: "Remember Me",
    forgot_password: "Forgot password?",
    forgot_password_message:
      "Enter your email address and we will send you a link to reset your password.",
    send_password_reset: "Send Password Reset Email",
    add: "Add",
    destination_example: "e.g Montreux",

    //new~
    exchange: "Exchange",
    history: "History",
    destHarbour: "Destination Harbour",
    ads_title: "My Ads",
    ads_info:
      "You can create one or more ads here. It's also here that you delete them.",
    ads_more:
      "Please delete your ads as soon as possible if you have an exchange, offer or request.",
    listings_title: "Listings",
    listings_info:
      "You can view the ads and click on the user to view these contact details and agree directly on the terms of exchange or other arrangements.",
    listings_more:
      "You can filter by offer request and exchange. You can also sort by columns.",
    boat_title: "My boat",
    boat_desc:
      "Put the specifications of your boat, they will be used automatically in your ads.",
    boat_more:
      "You can edit this information at any time, it is used in the ads to determine if the places of destination are adequate.",
    admin_panel: "Admin Panel",
    schedule_list: "Schedule List",
    user_list: "User List",
    loading: "Loading",

    myplace_example: "e.g Montreux",
    harbour_example: "e.g 15",
    ok: "OK",
    cancel: "CANCEL",
    clear: "CLEAR",

    german: "German",
    italian: "Italian",

    lading_heading: "Register your place exchange request!",
    leading_desc:
      "Want to spend a night in another port, arrive and have no visitor place available, it has happened to us all! With this platform, you have the opportunity to exchange your place with that of another individual. So you have the security of a place reserved for you in the port of your destination! To do this, simply register your request or find a browser interested in swapping its place on the page",
    gender: "Gender",
    boat_information: "Boat Information",
    boat_type: "Boat Type",
    my_harbour: "My Harbour",
    ads_information: "Ads Information",
    ads_type: "Ads Type",

    profile_saved_successfully: "Profile Saved Successfully",
    failed_to_save_profile: "Failed to Save Profile",
    success: "Success",
    failed: "Failed",
    upload_to_server_failed: "Upload to server failed",
    password_changed: "Password Changed",
    password_change_is_failed: "Password Changing is failed!",
    wrong_input: "Wrong Input",

    edit_btn: "Edit",
    save_btn: "Save",
    detail_view: "Detail View",

    detail: "Detail",
    acceptButton: "Accept",

    payment: "Payment Information",
    payment_desc: 'We are counting on your donation to continue the service exchange your port! Thank you for supporting us on the account defullservice-marketing Sàrl.- IBAN CH90 8047 9000 0153 0164 9',

    labelRowsPerPage: 'Rows per page:',
  },
  //French
  {
    app_title: "Échange ton port",
    english_native: "English",
    french_native: "Français",
    login: "Login",
    logout: "Déconnexion",
    register: "S'inscrire",
    profil: "Profil",
    civility: "Civilité",
    mr: "Monsieur",
    mrs: "Madame",
    ms: "Mademoiselle",
    first_name: "Prénom",
    enter_your_first_name: "Entrez votre prénom",
    last_name: "Nom",
    enter_your_last_name: "Entrez votre nom de famille",
    language: "Langue",
    english: "Anglais",
    french: "Français",
    enter_your_email: "Entrez votre Email",
    email: "Email",
    phone_number: "Numéro de téléphone",
    enter_your_phone_number: "Entrez votre numéro de téléphone portable",
    address: "Adresse",
    enter_your_addres: "Entrez votre adresse",
    address2: "Adresse 2",
    enter_your_postcode: "Entrez votre code postal",
    postcode: "Code postal",
    enter_your_city: "Entrez votre ville",
    town_city: "Ville",
    country: "Pays",
    profile_picture: "Photo de profil",
    add_profile_picture: "Ajouter une photo de profil",
    security: "Sécurité",
    password: "Mot de passe",
    enter_your_password: "Tapez votre mot de passe",
    change_password: "Modifier le mot de passe",
    old_password: "Ancien mot de passe",
    new_password: "Nouveau mot de passe",
    confirm_password: "Confirmez le mot de passe",
    change: "Modifier",
    change_email: "Modifier l'adresse Email",
    new_email: "Nouvelle adresse Email",
    save_my_profile: "Enregistrer mon profil",
    more: "Voir plus",
    boat_specification: "Spécifications du bateau",
    boat_name: "Nom du bateau",
    type: "Type",
    sail: "Voilier",
    motor: "Moteur",
    width: "Largeur",
    draught: "Tiran d'eau",
    harbour: "Mon port", //need to check
    my_place: "Ma place",
    save: "Sauvegarder",
    ads: "Mes annonces",
    offer: "Offre",
    demand: "Demande",
    boat: "Bateau",
    arrival: "Arrivée",
    return: "Départ",
    user_info: "Mon profil",
    boat_info: "Mon bateau",
    schedule: "Annonces",
    no: "Num",
    start_harbour: "départ",
    end_harbour: "arrivée",
    name: "Prénom",
    i_accept: "J'accepte",
    terms: "les termes et conditions générales",
    remember_me: "Se souvenir de moi",
    forgot_password: "Mot de passe oublié ?",
    forgot_password_message:
      "Entrez votre adresse email, vous recevrez un lien pour réinitialiser votre mot de passe.",
    send_password_reset: "Envoyer l'email de réinitialisation",
    add: "Ajouter",
    destination_example: "ex. Montreux",
    admin_panel: "Panneau d'administration",
    schedule_list: "Liste des horaires",
    user_list: "Liste d'utilisateur",
    loading: "Chargement",

    //new
    exchange: "Echange",
    history: "Histoire",
    destHarbour: "Port de destination",
    ads_title: "Mes annonces",
    ads_info:
      "Vous pouvez créer ici une ou plusieurs annonces. C’est également ici que vous les supprimez.",
    ads_more:
      "Merci de supprimer vos annonces aussi vite que possible si vous avez conclu un échange, offre ou demande.",
    listings_title: "Annonces",
    listings_info:
      "Vous pouvez consulter les annonces et cliquer sur l’utilisateur afin de voir ces coordonnées de contact et de convenir directement des modalités d’échange ou autres arrangements.",
    listings_more:
      "Vous pouvez filtrer par offre demande et échange. Vous pouvez également trier par colonnes.",
    boat_title: "Mon bateau",
    boat_desc:
      "Mettez les spécifications de votre bateau, elles seront utilisées automatiquement dans vos annonces.",
    boat_more:
      "Vous pouvez éditer ces informations à tout moment, elles sont utilisées dans les annonces afin de déterminer si les places de destination sont adéquates.",

    myplace_example: "Ex. Montreux",
    harbour_example: "Ex. 15",
    ok: "D'accord",
    cancel: "Annuler",
    clear: "clair",

    german: "German",
    italian: "Italian",

    lading_heading: "Enregistrer votre demande d'échange de place !",
    leading_desc:
      "Vouloir passer une nuit dans un autre port, arriver et ne pas avoir de place visiteur à disposition, ça nous est déjà arrivé à tous! Avec cette plateforme, vous avez la possibilité d'échanger votre place de port avec celle d'un autre particulier. Ainsi vous avez la sécurité d'une place réservée pour vous dans le port de votre destination! Pour cela, il vous sufffit d'enregistrez votre demande ou de trouver un navigateur intéressé à échanger sa place sur la page",
    gender: "Le genre",
    boat_information: "Informations sur le bateau",
    boat_type: "Type de bateau",
    my_harbour: "Mon port",
    ads_information: "Informations sur les annonces",
    ads_type: "Type d'annonce",

    profile_saved_successfully: "Profil enregistré avec succès",
    failed_to_save_profile: "Échec de l'enregistrement du profil",
    success: "Succès",
    failed: "Échoué",
    upload_to_server_failed: "Échec du téléchargement sur le serveur",
    password_changed: "Mot de passe changé",
    password_change_is_failed: "La modification du mot de passe a échoué!",
    wrong_input: "Mauvaise entrée",

    edit_btn: "Modifier",
    save_btn: "Sauvegarder",
    detail_view: "Vue détaillée",

    detail: "détail",
    acceptButton: "Accepter",

    payment: "Informations de payement",
    payment_desc: 'Nous comptons sur votre don pour continuer le service \'échange ton port\'! Merci de nous soutenir sur le compte de fullservice-marketing Sàrl.- IBAN CH90 8047 9000 0153 0164 9',

    labelRowsPerPage: 'Lignes par page:'
  },

  //german
  {
    app_title: "EXCHANGE TON PORT-German",
    login: "Login",
    logout: "Logout",
    register: "Register",
    profil: "Profile",
    civility: "Civility",
    mr: "Mr",
    mrs: "Mrs",
    ms: "Ms",
    enter_your_first_name: "Enter your First Name",
    first_name: "First Name",
    enter_your_last_name: "Enter your Last Name",
    last_name: "Last Name",
    language: "Language",
    english: "English",
    french: "French",
    enter_your_email: "Enter your Email",
    email: "Email",
    phone_number: "Phone Number",
    enter_your_phone_number: "Enter your Phone Number",
    address: "Address",
    address2: "Address2",
    enter_your_postcode: "Enter your Postcode",
    postcode: "Postcode",
    enter_your_city: "Enter your Town/City",
    town_city: "Town/City",
    country: "Country",
    profile_picture: "Profile Pictrue",
    add_profile_picture: "Add Profile Picture",
    security: "Security",
    password: "Password",
    enter_your_password: "Enter your password",
    change_password: "Change Password",
    old_password: "Old Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    change: "Change",
    change_email: "Change Email",
    new_email: "New Email",
    save_my_profile: "Save my Profile",
    more: "More",
    boat_specification: "Boat Specification",
    boat_name: "Boat Name",
    type: "Type",
    sail: "Sail",
    motor: "Motor",
    width: "Width",
    draught: "Draught",
    harbour: "My Harbour",
    my_place: "My place",
    save: "Save",
    ads: "My Ads",
    offer: "Offer",
    demand: "Demand",
    boat: "Boat",
    arrival: "Arrival",
    return: "Return",
    user_info: "User Info",
    boat_info: "Boat Info",
    schedule: "Listings",
    no: "No",
    start_harbour: "Start Harbour",
    end_harbour: "End Harbour",
    name: "Name",
    i_accept: "I accept",
    terms: "terms and conditions",
    remember_me: "Remember Me",
    forgot_password: "Forgot password?",
    forgot_password_message:
      "Enter your email address and we will send you a link to reset your password.",
    send_password_reset: "Send Password Reset Email",
    add: "Add",
    destination_example: "e.g Montreux",

    //new~
    exchange: "Exchange",
    history: "Geschichte",
    destHarbour: "Destination Harbour",
    ads_title: "My Ads",
    ads_info:
      "You can create one or more ads here. It's also here that you delete them.",
    ads_more:
      "Please delete your ads as soon as possible if you have an exchange, offer or request.",
    listings_title: "Listings",
    listings_info:
      "You can view the ads and click on the user to view these contact details and agree directly on the terms of exchange or other arrangements.",
    listings_more:
      "You can filter by offer request and exchange. You can also sort by columns.",
    boat_title: "My boat",
    boat_desc:
      "Put the specifications of your boat, they will be used automatically in your ads.",
    boat_more:
      "You can edit this information at any time, it is used in the ads to determine if the places of destination are adequate.",
    admin_panel: "Admin Panel",
    schedule_list: "Schedule List",
    user_list: "User List",
    loading: "Loading",

    myplace_example: "e.g Montreux",
    harbour_example: "e.g 15",
    ok: "OK",
    cancel: "CANCEL",
    clear: "CLEAR",

    german: "German",
    italian: "Italian"
  },

  //italian
  {
    app_title: "EXCHANGE TON PORT-Italian",
    login: "Login",
    logout: "Logout",
    register: "Register",
    profil: "Profile",
    civility: "Civility",
    mr: "Mr",
    mrs: "Mrs",
    ms: "Ms",
    enter_your_first_name: "Enter your First Name",
    first_name: "First Name",
    enter_your_last_name: "Enter your Last Name",
    last_name: "Last Name",
    language: "Language",
    english: "English",
    french: "French",
    enter_your_email: "Enter your Email",
    email: "Email",
    phone_number: "Phone Number",
    enter_your_phone_number: "Enter your Phone Number",
    address: "Address",
    address2: "Address2",
    enter_your_postcode: "Enter your Postcode",
    postcode: "Postcode",
    enter_your_city: "Enter your Town/City",
    town_city: "Town/City",
    country: "Country",
    profile_picture: "Profile Pictrue",
    add_profile_picture: "Add Profile Picture",
    security: "Security",
    password: "Password",
    enter_your_password: "Enter your password",
    change_password: "Change Password",
    old_password: "Old Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    change: "Change",
    change_email: "Change Email",
    new_email: "New Email",
    save_my_profile: "Save my Profile",
    more: "More",
    boat_specification: "Boat Specification",
    boat_name: "Boat Name",
    type: "Type",
    sail: "Sail",
    motor: "Motor",
    width: "Width",
    draught: "Draught",
    harbour: "My Harbour",
    my_place: "My place",
    save: "Save",
    ads: "My Ads",
    offer: "Offer",
    demand: "Demand",
    boat: "Boat",
    arrival: "Arrival",
    return: "Return",
    user_info: "User Info",
    boat_info: "Boat Info",
    schedule: "Listings",
    no: "No",
    start_harbour: "Start Harbour",
    end_harbour: "End Harbour",
    name: "Name",
    i_accept: "I accept",
    terms: "terms and conditions",
    remember_me: "Remember Me",
    forgot_password: "Forgot password?",
    forgot_password_message:
      "Enter your email address and we will send you a link to reset your password.",
    send_password_reset: "Send Password Reset Email",
    add: "Add",
    destination_example: "e.g Montreux",

    //new~
    exchange: "Exchange",
    history: "Storia",
    destHarbour: "Destination Harbour",
    ads_title: "My Ads",
    ads_info:
      "You can create one or more ads here. It's also here that you delete them.",
    ads_more:
      "Please delete your ads as soon as possible if you have an exchange, offer or request.",
    listings_title: "Listings",
    listings_info:
      "You can view the ads and click on the user to view these contact details and agree directly on the terms of exchange or other arrangements.",
    listings_more:
      "You can filter by offer request and exchange. You can also sort by columns.",
    boat_title: "My boat",
    boat_desc:
      "Put the specifications of your boat, they will be used automatically in your ads.",
    boat_more:
      "You can edit this information at any time, it is used in the ads to determine if the places of destination are adequate.",
    admin_panel: "Admin Panel",
    schedule_list: "Schedule List",
    user_list: "User List",
    loading: "Loading",

    myplace_example: "e.g Montreux",
    harbour_example: "e.g 15",
    ok: "OK",
    cancel: "CANCEL",
    clear: "CLEAR",

    german: "German",
    italian: "Italian"
  }
];

export default language;
